// completion.js — `azc completion` command.
// Generates shell completion scripts for bash, zsh, and fish.
// Users source the output in their shell profile:
//   source <(azc completion bash)
//   source <(azc completion zsh)
//   azc completion fish | source

const path = require('path');
const chalk = require('chalk');
const config = require('../config/config');

const REGIONS = [
  'uksouth', 'ukwest', 'westeurope', 'northeurope',
  'eastus', 'eastus2', 'westus2', 'centralus',
  'southeastasia', 'eastasia', 'australiaeast',
];

const COMMANDS = 'scan price compare plan config doctor completion';
const GLOBAL_FLAGS = '--quiet --no-color --verbose --version --help';

/**
 * List dynamic completable values.
 * Called internally by shell scripts via `azc completion --list <type>`.
 */
function listValues(type) {
  if (type === 'subscriptions') {
    const cfg = config.loadConfig();
    const subs = Object.keys(cfg.subscriptions || {});
    subs.forEach((s) => process.stdout.write(s + '\n'));
  } else if (type === 'services') {
    const mappings = require(path.join(__dirname, '../../data/sku-mappings.json'));
    const aliases = new Set();
    for (const entry of Object.values(mappings.services)) {
      entry.aliases.forEach((a) => aliases.add(a));
    }
    [...aliases].sort().forEach((a) => process.stdout.write(a + '\n'));
  } else if (type === 'regions') {
    REGIONS.forEach((r) => process.stdout.write(r + '\n'));
  }
}

/**
 * Generate bash completion script.
 */
function generateBash() {
  const regions = REGIONS.join(' ');
  return `# azc bash completion — generated by azc completion bash
_azc_completions() {
  local cur prev cmd
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  cmd="\${COMP_WORDS[1]}"

  if [ "\$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=($(compgen -W "${COMMANDS}" -- "\$cur"))
    return
  fi

  case "\$cmd" in
    scan)
      case "\$prev" in
        --subscription|-s) COMPREPLY=($(compgen -W "$(azc completion --list subscriptions 2>/dev/null)" -- "\$cur")); return;;
        --format|-f) COMPREPLY=($(compgen -W "table json" -- "\$cur")); return;;
        --region|-r) COMPREPLY=($(compgen -W "${regions}" -- "\$cur")); return;;
        --currency|-c) COMPREPLY=($(compgen -W "GBP USD EUR" -- "\$cur")); return;;
        --out|-o) COMPREPLY=($(compgen -f -- "\$cur")); return;;
      esac
      COMPREPLY=($(compgen -W "--subscription --resource-group --out --format --region --currency --group --no-group --no-ri ${GLOBAL_FLAGS}" -- "\$cur"))
      ;;
    price)
      case "\$prev" in
        --region|-r) COMPREPLY=($(compgen -W "${regions}" -- "\$cur")); return;;
        --os) COMPREPLY=($(compgen -W "linux windows" -- "\$cur")); return;;
        --currency|-c) COMPREPLY=($(compgen -W "GBP USD EUR" -- "\$cur")); return;;
      esac
      COMPREPLY=($(compgen -W "--region --os --currency ${GLOBAL_FLAGS}" -- "\$cur"))
      ;;
    compare)
      case "\$prev" in
        --subscription|-s) COMPREPLY=($(compgen -W "$(azc completion --list subscriptions 2>/dev/null)" -- "\$cur")); return;;
        --format|-f) COMPREPLY=($(compgen -W "table json" -- "\$cur")); return;;
        --region|-r) COMPREPLY=($(compgen -W "${regions}" -- "\$cur")); return;;
        --currency|-c) COMPREPLY=($(compgen -W "GBP USD EUR" -- "\$cur")); return;;
      esac
      COMPREPLY=($(compgen -W "--subscription --with --name --region --currency --format ${GLOBAL_FLAGS}" -- "\$cur"))
      ;;
    plan)
      case "\$prev" in
        --region|-r) COMPREPLY=($(compgen -W "${regions}" -- "\$cur")); return;;
        --currency|-c) COMPREPLY=($(compgen -W "GBP USD EUR" -- "\$cur")); return;;
        --format|-f) COMPREPLY=($(compgen -W "table json" -- "\$cur")); return;;
        --load|-l|--out|-o) COMPREPLY=($(compgen -f -- "\$cur")); return;;
      esac
      COMPREPLY=($(compgen -W "--interactive --load --last --region --currency --format --out --quick --no-ri ${GLOBAL_FLAGS}" -- "\$cur"))
      ;;
    config)
      if [ "\$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=($(compgen -W "show get set add-sub remove-sub path" -- "\$cur"))
        return
      fi
      ;;
    doctor)
      COMPREPLY=($(compgen -W "${GLOBAL_FLAGS}" -- "\$cur"))
      ;;
    completion)
      if [ "\$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=($(compgen -W "bash zsh fish" -- "\$cur"))
        return
      fi
      ;;
  esac
}

complete -F _azc_completions azc
`;
}

/**
 * Generate zsh completion script.
 */
function generateZsh() {
  const regions = REGIONS.map((r) => `'${r}'`).join(' ');
  return `#compdef azc
# azc zsh completion — generated by azc completion zsh

_azc() {
  local -a commands
  commands=(
    'scan:Scan a subscription and estimate costs'
    'price:Look up pricing for a single resource'
    'compare:Compare costs against a SKU change'
    'plan:Build a cost estimate interactively'
    'config:View and modify configuration'
    'doctor:Check your azc setup'
    'completion:Generate shell completions'
  )

  _arguments -C \\
    '1:command:->command' \\
    '*::arg:->args'

  case "\$state" in
    command) _describe 'azc commands' commands;;
    args)
      case "\$words[1]" in
        scan)
          _arguments \\
            '(-s --subscription)'{-s,--subscription}'[Subscription]:subscription:->subs' \\
            '(-g --resource-group)'{-g,--resource-group}'[Resource group]:group:' \\
            '(-o --out)'{-o,--out}'[Output file]:file:_files' \\
            '(-f --format)'{-f,--format}'[Format]:format:(table json)' \\
            '(-r --region)'{-r,--region}'[Region]:region:(${regions.replace(/'/g, '')})' \\
            '(-c --currency)'{-c,--currency}'[Currency]:currency:(GBP USD EUR)' \\
            '--no-ri[Skip RI recommendations]' \\
            '--no-group[Flat output]'
          ;;
        price)
          _arguments \\
            '1:query:' \\
            '(-r --region)'{-r,--region}'[Region]:region:(${regions.replace(/'/g, '')})' \\
            '--os[OS type]:os:(linux windows)' \\
            '(-c --currency)'{-c,--currency}'[Currency]:currency:(GBP USD EUR)'
          ;;
        compare)
          _arguments \\
            '(-s --subscription)'{-s,--subscription}'[Subscription]:subscription:->subs' \\
            '(-w --with)'{-w,--with}'[Change spec]:spec:' \\
            '--name[Resource name]:name:' \\
            '(-r --region)'{-r,--region}'[Region]:region:(${regions.replace(/'/g, '')})' \\
            '(-c --currency)'{-c,--currency}'[Currency]:currency:(GBP USD EUR)' \\
            '(-f --format)'{-f,--format}'[Format]:format:(table json)'
          ;;
        plan)
          _arguments \\
            '(-i --interactive)'{-i,--interactive}'[Interactive mode]' \\
            '(-l --load)'{-l,--load}'[Load estimate]:file:_files' \\
            '--last[Load most recent estimate]' \\
            '(-r --region)'{-r,--region}'[Region]:region:(${regions.replace(/'/g, '')})' \\
            '(-c --currency)'{-c,--currency}'[Currency]:currency:(GBP USD EUR)' \\
            '(-f --format)'{-f,--format}'[Format]:format:(table json)' \\
            '(-o --out)'{-o,--out}'[Output file]:file:_files' \\
            '(-q --quick)'{-q,--quick}'[Quick start template]' \\
            '--no-ri[Skip RI recommendations]'
          ;;
        config)
          _arguments '1:subcommand:(show get set add-sub remove-sub path)'
          ;;
        completion)
          _arguments '1:shell:(bash zsh fish)'
          ;;
      esac
      ;;
  esac

  case "\$state" in
    subs) compadd $(azc completion --list subscriptions 2>/dev/null);;
  esac
}

_azc "\$@"
`;
}

/**
 * Generate fish completion script.
 */
function generateFish() {
  const lines = [
    '# azc fish completion — generated by azc completion fish',
    '',
    '# Commands',
    "complete -c azc -n '__fish_use_subcommand' -a 'scan' -d 'Scan a subscription'",
    "complete -c azc -n '__fish_use_subcommand' -a 'price' -d 'Look up pricing'",
    "complete -c azc -n '__fish_use_subcommand' -a 'compare' -d 'Compare costs'",
    "complete -c azc -n '__fish_use_subcommand' -a 'plan' -d 'Build an estimate'",
    "complete -c azc -n '__fish_use_subcommand' -a 'config' -d 'View/modify config'",
    "complete -c azc -n '__fish_use_subcommand' -a 'doctor' -d 'Check setup'",
    "complete -c azc -n '__fish_use_subcommand' -a 'completion' -d 'Shell completions'",
    '',
    '# scan flags',
    "complete -c azc -n '__fish_seen_subcommand_from scan' -s s -l subscription -d 'Subscription' -xa '(azc completion --list subscriptions 2>/dev/null)'",
    "complete -c azc -n '__fish_seen_subcommand_from scan' -s g -l resource-group -d 'Resource group'",
    "complete -c azc -n '__fish_seen_subcommand_from scan' -s o -l out -d 'Output file' -F",
    "complete -c azc -n '__fish_seen_subcommand_from scan' -s f -l format -d 'Format' -xa 'table json'",
    "complete -c azc -n '__fish_seen_subcommand_from scan' -s r -l region -d 'Region' -xa '" + REGIONS.join(' ') + "'",
    "complete -c azc -n '__fish_seen_subcommand_from scan' -s c -l currency -d 'Currency' -xa 'GBP USD EUR'",
    "complete -c azc -n '__fish_seen_subcommand_from scan' -l no-ri -d 'Skip RI recommendations'",
    "complete -c azc -n '__fish_seen_subcommand_from scan' -l no-group -d 'Flat output'",
    '',
    '# price flags',
    "complete -c azc -n '__fish_seen_subcommand_from price' -s r -l region -d 'Region' -xa '" + REGIONS.join(' ') + "'",
    "complete -c azc -n '__fish_seen_subcommand_from price' -l os -d 'OS' -xa 'linux windows'",
    "complete -c azc -n '__fish_seen_subcommand_from price' -s c -l currency -d 'Currency' -xa 'GBP USD EUR'",
    '',
    '# compare flags',
    "complete -c azc -n '__fish_seen_subcommand_from compare' -s s -l subscription -d 'Subscription' -xa '(azc completion --list subscriptions 2>/dev/null)'",
    "complete -c azc -n '__fish_seen_subcommand_from compare' -s w -l with -d 'Change spec'",
    "complete -c azc -n '__fish_seen_subcommand_from compare' -l name -d 'Resource name'",
    "complete -c azc -n '__fish_seen_subcommand_from compare' -s r -l region -d 'Region' -xa '" + REGIONS.join(' ') + "'",
    "complete -c azc -n '__fish_seen_subcommand_from compare' -s c -l currency -d 'Currency' -xa 'GBP USD EUR'",
    "complete -c azc -n '__fish_seen_subcommand_from compare' -s f -l format -d 'Format' -xa 'table json'",
    '',
    '# plan flags',
    "complete -c azc -n '__fish_seen_subcommand_from plan' -s i -l interactive -d 'Interactive mode'",
    "complete -c azc -n '__fish_seen_subcommand_from plan' -s l -l load -d 'Load estimate' -F",
    "complete -c azc -n '__fish_seen_subcommand_from plan' -l last -d 'Load most recent'",
    "complete -c azc -n '__fish_seen_subcommand_from plan' -s r -l region -d 'Region' -xa '" + REGIONS.join(' ') + "'",
    "complete -c azc -n '__fish_seen_subcommand_from plan' -s c -l currency -d 'Currency' -xa 'GBP USD EUR'",
    "complete -c azc -n '__fish_seen_subcommand_from plan' -s f -l format -d 'Format' -xa 'table json'",
    "complete -c azc -n '__fish_seen_subcommand_from plan' -s o -l out -d 'Output file' -F",
    "complete -c azc -n '__fish_seen_subcommand_from plan' -s q -l quick -d 'Quick start'",
    "complete -c azc -n '__fish_seen_subcommand_from plan' -l no-ri -d 'Skip RI recommendations'",
    '',
    '# config subcommands',
    "complete -c azc -n '__fish_seen_subcommand_from config' -xa 'show get set add-sub remove-sub path'",
    '',
    '# completion shells',
    "complete -c azc -n '__fish_seen_subcommand_from completion' -xa 'bash zsh fish'",
    '',
  ];

  return lines.join('\n');
}

/**
 * Register the completion command.
 */
module.exports = function registerCompletionCommand(program) {
  program
    .command('completion')
    .description('Generate shell completion scripts')
    .argument('<shell>', 'Shell type: bash, zsh, or fish')
    .option('--list <type>', 'List completable values (used by completion scripts)')
    .action((shell, opts) => {
      // Hidden --list flag for dynamic completion
      if (opts.list) {
        listValues(opts.list);
        return;
      }

      const shellLower = shell.toLowerCase();
      let script;

      switch (shellLower) {
        case 'bash':
          script = generateBash();
          break;
        case 'zsh':
          script = generateZsh();
          break;
        case 'fish':
          script = generateFish();
          break;
        default:
          process.stderr.write(chalk.red(`Unknown shell: ${shell}. Supported: bash, zsh, fish\n`));
          process.exit(1);
      }

      process.stdout.write(script);
      process.stderr.write(chalk.dim(`\n# Add to your shell profile:\n#   source <(azc completion ${shellLower})\n`));
    });
};
